# Title, decription, tagline and URL for your site
# Can be used in your theme by calling 'site.title' and so on
title: Cleanflight
url: http://localhost:3000

# Used so Jekyll outputs the site correctly so Gulp can do what it wants
source: src
destination: serve

# Same as the title etc for your site but can instead be
# called by using 'site.author.name' and so on
author:
  name: Kevin Granger
  email: shipowlata@gmail.com
  twitter: https://twitter.com/Kevin_Granger

# general setting for Jekyll
googleAnalytics: UA-XXXXX-X


# _config.build.yml overwrites these options when you run `gulp build`
# Enables future posts (posts with dates in the future) and drafts
future: true
show_drafts: false
# Disables the more accurate related posts for faster generating of the site
lsi: false
limit_posts: 10

# Permalink structure and pagination options
relative_permalinks: true
permalink: /:categories/:title
paginate: 1000
paginate_path: 'page:num'
excerpt_separator: '<!--more-->'

# Markdown library
markdown: redcarpet
# Markdown library options
redcarpet:
  extensions: ['no_intra_emphasis', 'tables', 'fenced_code_blocks', 'autolink', 'smart',
              'strikethrough', 'superscript', 'underline', 'highlight', 'footnotes']
highlighter: true

algolia:
  index_name: dev_cleanflight
  application_id: T2ZX9HO66V
  search_only_api_key: 7119d2f6f1cd95224251ec2e490e824f
